name: movie-picture-backend-build

on:
  workflow_dispatch:
      
  pull_request:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          node-version: latest
          cache: 'pip'

      - name: Install dependencies
        run: cd starter/backend && pipenv install

      - name: Python Linter
        run: cd starter/backend && pipenv run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          node-version: latest
          cache: 'pip'

      - name: Install dependencies
        run: cd starter/backend && pipenv install

      - name: Test with pytest
        run: cd starter/backend && pipenv run test
        continue-on-error: false

    
  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          node-version: latest
          cache: 'pip'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test with pytest
        run: cd starter/backend && pipenv run test
        continue-on-error: false